---
title: "Recall segments paired"
author: "Hilmar Berger"
date: "6/23/2020"
output: html_document
---

```{r, message=FALSE}
library(DNAcopy)
library(modeest)
library(data.table)
library(ggplot2)
library(readxl)
```

```{r}
input_folder_total_counts = "/data_genome1/MB208_WGS/seqs/2020-05/"

read_cnts_raw = read.table(file.path(input_folder_total_counts,"MB208_WGS_DNA_count_table.txt"),sep="\t",header=F, as.is=T, colClasses=c(rep("character",6), "integer") )
colnames(read_cnts_raw) = c("sample","run","index","lane","mate_end","replicate","count")
read_cnts_raw = read_cnts_raw[order(read_cnts_raw$run, read_cnts_raw$lane),]
read_cnts_raw$run_lane = factor(paste(read_cnts_raw$run, read_cnts_raw$lane))
read_cnts_raw$sample_id_orig = paste(read_cnts_raw$run, read_cnts_raw$lane, paste(read_cnts_raw$sample,read_cnts_raw$replicate,sep="-"), gsub(" ", "", gsub("R","",read_cnts_raw$mate_end)), sep="_")

read_cnts_raw$sample =  gsub("B5G", "", read_cnts_raw$sample)

read_cnts_per_sample = as.data.table(read_cnts_raw)[, .(count=sum(count)), by="sample"]
setkey(read_cnts_per_sample, "sample")
count_ratios = c("MOUlyuRAAABAAA" = read_cnts_per_sample["MOUlyuRAAABAAA"]$count / read_cnts_per_sample["MOUlyuRAAAAAAA"]$count, 
                 "MOUlyuRAAACAAA" = read_cnts_per_sample["MOUlyuRAAACAAA"]$count / read_cnts_per_sample["MOUlyuRAAAAAAA"]$count, 
                 "MOUlyuRAAAEAAA" = read_cnts_per_sample["MOUlyuRAAAEAAA"]$count / read_cnts_per_sample["MOUlyuRAAADAAA"]$count, 
                 "MOUlyuRAAAFAAA" = read_cnts_per_sample["MOUlyuRAAAFAAA"]$count / read_cnts_per_sample["MOUlyuRAAADAAA"]$count)
```


```{r, warning=FALSE}
ed = as.data.frame(read_xls("../../../metadata/SampleDescription_WGS.xls", sheet = 1))

rownames(ed) = ed$SampleID
single_samples = ed$SampleID

reload_data = T
if(reload_data) {
  all_tables_paired = list()
  
  tmp = list.dirs(path="..", recursive=F)
  paired_sample_calls_folders = tmp[!grepl("*_single$|BAF",tmp) & grepl("MOU*", tmp)]
  
  input_files_ratio = list()
  for (ff in paired_sample_calls_folders) {
    s = gsub("_single", "", basename(ff))
    input_files_ratio[[s]] = list.files(path=ff, pattern="_ratio.txt$", full.names=T )
  }
  
  for (s in names(input_files_ratio)) {
    f = input_files_ratio[[s]]
    tmp = read.table(f, sep="\t", header=T, stringsAsFactors = F)
    #colnames(tmp) = c("seq","start","cnt")
    #tmp$sample = paste(s, ed[s,]$Name, sep="_")
    tmp$sample = s
    tmp$log2ratio = ifelse(tmp$Ratio < 0, NA, log2(tmp$Ratio))
    all_tables_paired[[s]] = tmp
  }
  save(all_tables_paired, file="All_Raw_LogRatio_Profiles_paired.Rdata")
} else {
  load("All_Raw_LogRatio_Profiles_paired.Rdata")
}

all_CNV_paired = do.call(rbind, all_tables_paired)
```



```{r}
sample_modes = unlist(lapply(all_tables_paired, function(x) mlv(x$log2ratio, method="Venter", na.rm=T)))

barplot(sample_modes, las=2, ylab="Mode (Venter)", main="Sample Modes of LogRatios as generated by ControlFreeC", ylim=c(-1,1))
points(1:4, log2(count_ratios))
abline(h=0, col="red")
```

Sample modes (and similarly medians) are somewhat shifted from the 0 of the log2ratios, however, this does not seem to correlate to differences in total read counts per sample pair, so we rather will keep the results as they are. 


```{r}
all_segments = list()
all_pruned_segments = list()

# This gets a table with segments for a single chromosome and returns one with all consecutive segments with min_diff < threshold joined
prune_segments_chromosome = function(x, min_diff = 0.05) {
  
  reduce_rows = function(r1,r2) {
    if(abs(r1$seg.mean - r2$seg.mean) < min_diff) {
      tmp = r1
      tmp$seg.mean = mean(c(r1$seg.mean, r2$seg.mean))
      tmp$loc.start = r1$loc.start
      tmp$loc.end = r2$loc.end
      tmp$num.mark = sum(r1$num.mark, r2$num.mark)
      return(tmp)
    } else {
      return(r2)
    }
  }

  zz = as.data.frame(do.call(rbind, Reduce(reduce_rows, split(x, 1:nrow(x)), accumulate = T)))
  zz$width = zz$loc.end - zz$loc.start
  max_dist = tapply(zz$width, zz$loc.start, max)
  zz$max_width = max_dist[as.character(zz$loc.start)]
  
  return(subset(zz, width==max_width))
}  

prune_segments_sample <- function(x, min_diff) {
  
  per_chrom_data = split(x, x$chrom)
  rr = do.call(rbind, Map(prune_segments_chromosome, per_chrom_data, min_diff))
}

for (n in names(all_tables_paired)) {
  tmp = all_tables_paired[[n]][,c("Ratio","Chromosome","Start")]
  tmp$log2ratio = ifelse(tmp$Ratio == -1, NA, log2(tmp$Ratio))
  tmp = subset(tmp, !is.na(log2ratio))
  s_mode = mlv(tmp$log2ratio, method="Venter", na.rm=T)
  if(abs(s_mode)==0) {
    CNA.object <- CNA(tmp$log2ratio, tmp$Chromosome, tmp$Start, data.type="logratio", sampleid = n)  
  } else {
    CNA.object <- CNA(tmp$log2ratio - s_mode, tmp$Chromosome, tmp$Start, data.type="logratio", sampleid = n)  
  }
  
  smoothed.CNA.object <- smooth.CNA(CNA.object)
  segment.smoothed.CNA.object <- segment(smoothed.CNA.object, verbose=1, undo.splits = "sdundo", undo.SD=3 )
  all_segments[[n]] = segment.smoothed.CNA.object
  
  ps = prune_segments_sample(segment.smoothed.CNA.object$output, 0.05)
  
  ps$status = ifelse(ps$seg.mean > 0.15, "gain", ifelse(ps$seg.mean < -0.15, "loss", "nc") )
  ps$copy.number = 2**ps$seg.mean * 2
  
  all_pruned_segments[[ n ]] = ps
  
}
```


```{r, fig.width=12}
for (n in names(all_pruned_segments)) {
  print(ggplot(all_pruned_segments[[n]]) + geom_segment(aes(y=seg.mean, yend=seg.mean, x=loc.start, xend=loc.end, col=status)) + facet_wrap(chrom~. , nrow = 1)  + ggtitle(n) + coord_cartesian(ylim=c(-2,2)))
}

```

```{r}
all_long_CN_calls = lapply(all_pruned_segments, function(x) {colnames(x) = c("sample","chr","start","end","num.mark","seg.mean","width","max_width","status","copy.number"); return(x[,colnames(x) != "max_width"])})

save(all_long_CN_calls, file="All_CNV_segments_paired_recalled.Rdata")
```




# Software versions

```{r}
sessionInfo()
```

