---
title: "MB208 Indels"
author: "Hilmar Berger"
output:
 html_document:
    toc: true
    toc_depth: 3
    toc_float: false
    number_sections: true
    code_folding: hide
    
pdf_document:
    fig_caption: true
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
---

```{r}
library(data.table)
library(ggplot2)
library(pheatmap)
library(reshape2)
library(ggthemes)
library(xlsx)
```

```{r}
ed = read.xlsx("../../../metadata/SampleDescription_WGS.xls", sheetIndex = 1, stringsAsFactors=F)
rownames(ed) = ed$SampleID
#ed$MouseID = "M"
ed$SampleDesc = paste(ed$MouseID, " ", ed$Name, sep="")
ed = subset(ed, MouseID %in% c(1,2))
```


```{r, fig.width = 18}
d = read.table("indel_counts_clonal.csv", sep="\t", header=T)
colnames(d) = gsub("Colibactin..","",colnames(d))
dm = as.matrix(d[, 5:ncol(d)])
rownames(dm) = with(d, paste(Type, Subtype, Indel_size, Repeat_MH_size, sep="_"))


pheatmap(t(dm), scale="none", fontsize_row = 24, main="Absolute indel numbers per class")

pheatmap(t(dm), scale="row", fontsize_row = 24, main="Z-scored counts per class")

```

```{r, fig.width=18}

dm_ts = reshape2::melt(dm, value.vars = c("NI", "Wnt_Independent") )
colnames(dm_ts) = c("IndelClass", "Sample", "Count")

dm_ts = merge(dm_ts, ed, by.x="Sample", by.y="SampleID", all.x=T, sort=F)

totals = tapply(dm_ts$Count, dm_ts$Sample, sum)
dm_ts$Prop = dm_ts$Count / totals[dm_ts$Sample]

ggplot(dm_ts, aes(x=IndelClass, y = Count, fill=Sample)) + geom_bar(stat = "Identity", position = "dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))


ggplot(dm_ts, aes(x=IndelClass, y = Prop, fill=Sample)) + geom_bar(stat = "Identity", position = "dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))

```


```{r, fig.width=14, fig.height=4}
sigs.input = t(dm)
rownames(sigs.input) = ed[rownames(sigs.input), "Sample.Description."]
sigs.input_rel = sweep(sigs.input, 1, apply(sigs.input, 1, sum), "/")

sigs.input_rel_diff = rbind(sigs.input_rel["WI_Clone1",]-sigs.input_rel["NI_Clone1",], sigs.input_rel["WI_Clone2",]-sigs.input_rel["NI_Clone2",])
rownames(sigs.input_rel_diff) = c("WI_Clone1", "WI_Clone2")


tmp = as.data.frame(sigs.input_rel)
tmp$sample = rownames(tmp)
sigs.input_rel_ts = as.data.frame(reshape2::melt(tmp))
colnames(sigs.input_rel_ts) = c("sampleID", "nc","prop")
sigs.input_rel_ts$group = substr(sigs.input_rel_ts$sampleID,1,8)
sigs.input_rel_ts$replicate = substr(sigs.input_rel_ts$sampleID,9,9)

p = ggplot(sigs.input_rel_ts) + geom_col(aes(x=nc, fill=replicate, y = prop), position="dodge") + theme_few() + theme(axis.text.x = element_text(angle=90, hjust=1) ) + xlab("") + ylab("Proportion") + labs(fill="Sample") + facet_grid(group ~ .)
print(p)

tmp = as.data.frame(sigs.input_rel_diff)
tmp$sample = rownames(tmp)
sigs.input_diff_ts = as.data.frame(reshape2::melt(tmp))
colnames(sigs.input_diff_ts) = c("sampleID", "nc","prop")
sigs.input_diff_ts$group = "Subtracted"
sigs.input_diff_ts$replicate = substr(sigs.input_diff_ts$sampleID,9,9)

sigs.input_combined_ts = rbind(sigs.input_rel_ts, sigs.input_diff_ts)
sigs.input_combined_ts$group = factor(sigs.input_combined_ts$group, levels=c("WI_Clone","NI_Clone","Subtracted"))

sigs.input_combined_ts$id_class_long = unlist(sapply(strsplit(as.character(sigs.input_combined_ts$nc), "_"), function(x) paste(x[1:3], collapse="_")))
sigs.input_combined_ts$id_class_short = unlist(sapply(strsplit(as.character(sigs.input_combined_ts$nc), "_"), function(x) paste(x[1:2], collapse="_")))
sigs.input_combined_ts$id_class_steps = unlist(sapply(strsplit(as.character(sigs.input_combined_ts$nc), "_"), function(x) paste(x[length(x)], collapse="_")))
classes_to_final = c("DEL_C_1"="C del","DEL_MH_2"="2bp","DEL_MH_3"="3bp","DEL_MH_4"="4bp","DEL_MH_5+"="5bp+","DEL_repeats_2"="2bp del","DEL_repeats_3"="3bp del","DEL_repeats_4"="4bp del","DEL_repeats_5+"="5bp+ del","DEL_T_1"="T del","INS_C_1"="C ins","INS_repeats_2"="2bp ins","INS_repeats_3"="3bp ins","INS_repeats_4"="4bp ins","INS_repeats_5+"="5bp+ ins","INS_T_1"="T ins")

level_order = c("C del","T del","C ins","T ins","2bp del","3bp del","4bp del","5bp+ del","2bp ins","3bp ins","4bp ins","5bp+ ins","2bp","3bp","4bp","5bp+")
sigs.input_combined_ts$id_class_final = factor(classes_to_final[sigs.input_combined_ts$id_class_long], levels=level_order)

p = ggplot(sigs.input_combined_ts) + geom_col(aes(x=id_class_steps, fill=replicate, y = prop), position=position_dodge2()) + theme_few() + theme(panel.border = element_blank(), panel.spacing.x = unit(1,"points"), strip.background = element_rect(fill = "grey90")) + xlab("") + ylab("Proportion") + labs(fill="Replicate") + facet_grid(group ~ id_class_final, scales = "free_x",space = "free_x") + scale_y_continuous(limits=c(0,1)) + coord_cartesian(ylim=c(0,0.32))
print(p)

```

```{r}
pdf("InDel_profile_clonal.pdf", width=14, height = 4)
print(p)
dev.off()
```

